workflows:
  smart-assistant-android-build:
    name: Smart Assistant Android Build
    # working_directory: apps/smart_assistant_new # Melos will handle this
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.16.2
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install Melos
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          flutter pub global activate melos
          melos bootstrap
      - name: Set up Flutter and Android
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          melos exec --scope=smart_assistant_new -- flutter clean
          melos exec --scope=smart_assistant_new -- flutter pub get
          melos exec --scope=smart_assistant_new -- flutter doctor -v
          melos exec --scope=smart_assistant_new -- ./gradlew clean --no-daemon
      - name: Build Android
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          melos exec --scope=smart_assistant_new -- flutter build apk --release
    artifacts:
      - apps/smart_assistant_new/build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ibrahimalsattouf88@gmail.com
        notify:
          success: true
          failure: true

  control-panel-android-build:
    name: Control Panel Android Build
    # working_directory: apps/control_panel_new # Melos will handle this
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.16.2
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install Melos
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          flutter pub global activate melos
          melos bootstrap
      - name: Set up Flutter and Android
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          melos exec --scope=control_panel_new -- flutter clean
          melos exec --scope=control_panel_new -- flutter pub get
          melos exec --scope=control_panel_new -- flutter doctor -v
          melos exec --scope=control_panel_new -- ./gradlew clean --no-daemon
      - name: Build Android
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          melos exec --scope=control_panel_new -- flutter build apk --release
    artifacts:
      - apps/control_panel_new/build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ibrahimalsattouf88@gmail.com
        notify:
          success: true
          failure: true

