workflows:
  smart-assistant-android-build:
    name: Smart Assistant Android Build
    working_directory: apps/smart_assistant
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.16.2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ibrahimalsattouf88@gmail.com
        notify:
          success: true
          failure: true

  control-panel-android-build:
    name: Control Panel Android Build
    working_directory: apps/control_panel
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.16.2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ibrahimalsattouf88@gmail.com
        notify:
          success: true
          failure: true

