workflows:
  android_smart_assistant:
    name: Android (Smart Assistant)
    environment:
      flutter: stable
    scripts:
      - flutter --version
      - dart --version || true
      - dart pub global activate melos
      - echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> $CM_ENV
      - melos bootstrap # Run melos bootstrap from the root
      - |
        melos exec --scope="smart_assistant_new" -- \
        bash -c '
          cd apps/smart_assistant_new && \
          flutter pub get && \
          if [ ! -f android/gradlew ]; then \
            echo "android/gradlew missing → regenerating Android/iOS"; \
            rm -rf android ios; \
            flutter create .; \
            flutter pub get; \
          fi; \
          chmod +x android/gradlew || true; \
          flutter build apk --release
        '
    artifacts:
      - apps/smart_assistant_new/build/app/outputs/flutter-apk/*.apk
      - apps/smart_assistant_new/build/**/outputs/**/*.aab
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - .dart_tool
        - apps/smart_assistant_new/.dart_tool
        - apps/smart_assistant_new/build

  android_control_panel:
    name: Android (Control Panel)
    environment:
      flutter: stable
    scripts:
      - flutter --version
      - dart --version || true
      - dart pub global activate melos
      - echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> $CM_ENV
      - melos bootstrap # Run melos bootstrap from the root
      - |
        melos exec --scope="control_panel_new" -- \
        bash -c '
          cd apps/control_panel_new && \
          flutter pub get && \
          if [ ! -f android/gradlew ]; then \
            echo "android/gradlew missing → regenerating Android/iOS"; \
            rm -rf android ios; \
            flutter create .; \
            flutter pub get; \
          fi; \
          chmod +x android/gradlew || true; \
          flutter build apk --release
        '
    artifacts:
      - apps/control_panel_new/build/app/outputs/flutter-apk/*.apk
      - apps/control_panel_new/build/**/outputs/**/*.aab
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - .dart_tool
        - apps/control_panel_new/.dart_tool
        - apps/control_panel_new/build

