name: Codemagic AutoFix (final)

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cm-autofix-final
  cancel-in-progress: false

jobs:
  smart:
    name: Build smart-assistant-app on Codemagic
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Codemagic (smart)
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          token: ${{ secrets.CODEMAGIC_TOKEN }}
          app-id: ${{ secrets.CODEMAGIC_APP_SMART }}
          workflow-id: ${{ secrets.CODEMAGIC_WORKFLOW_SMART }}
          branch: main

  panel:
    name: Build control-panel-app on Codemagic
    runs-on: ubuntu-latest
    needs: smart
    steps:
      - name: Trigger Codemagic (panel)
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          token: ${{ secrets.CODEMAGIC_TOKEN }}
          app-id: ${{ secrets.CODEMAGIC_APP_PANEL }}
          workflow-id: ${{ secrets.CODEMAGIC_WORKFLOW_PANEL }}
          branch: main
