name: Codemagic AutoBuild (final)
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-codemagic-token:
    runs-on: ubuntu-latest
    steps:
      - name: Print diagnostics (x-auth-token)
        run: |
          echo "== GET /apps with x-auth-token =="
          curl -sS -i -X GET "https://api.codemagic.io/apps?teamId=${{ secrets.CODEMAGIC_TEAM_ID }}" \
            -H "x-auth-token: ${{ secrets.CODEMAGIC_TOKEN }}" || true
      - name: Print diagnostics (Authorization Bearer)
        run: |
          echo "== GET /apps with Authorization: Bearer =="
          curl -sS -i -X GET "https://api.codemagic.io/apps?teamId=${{ secrets.CODEMAGIC_TEAM_ID }}" \
            -H "Authorization: Bearer ${{ secrets.CODEMAGIC_TOKEN }}" || true

  smart:
    name: Build smart-assistant-app on Codemagic
    needs: verify-codemagic-token
    runs-on: ubuntu-latest
    steps:
      - name: Trigger via Action (smart)
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          token: ${{ secrets.CODEMAGIC_TOKEN }}
          app-id: ${{ secrets.CODEMAGIC_APP_SMART }}
          workflow-id: ${{ secrets.CODEMAGIC_WORKFLOW_SMART }}
          branch: main
      - name: Fallback trigger via API (smart) if Action failed
        if: failure()
        run: |
          cat >payload.json <<JSON
          {
            "appId": "${{ secrets.CODEMAGIC_APP_SMART }}",
            "workflowId": "${{ secrets.CODEMAGIC_WORKFLOW_SMART }}",
            "branch": "main",
            "teamId": "${{ secrets.CODEMAGIC_TEAM_ID }}"
          }
          JSON
          echo "== POST /builds (fallback smart) =="
          curl -sS -i -X POST https://api.codemagic.io/builds \
            -H "Content-Type: application/json" \
            -H "x-auth-token: ${{ secrets.CODEMAGIC_TOKEN }}" \
            -d @payload.json

  panel:
    name: Build control-panel-app on Codemagic
    needs: smart
    runs-on: ubuntu-latest
    steps:
      - name: Trigger via Action (panel)
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          token: ${{ secrets.CODEMAGIC_TOKEN }}
          app-id: ${{ secrets.CODEMAGIC_APP_PANEL }}
          workflow-id: ${{ secrets.CODEMAGIC_WORKFLOW_PANEL }}
          branch: main
      - name: Fallback trigger via API (panel) if Action failed
        if: failure()
        run: |
          cat >payload.json <<JSON
          {
            "appId": "${{ secrets.CODEMAGIC_APP_PANEL }}",
            "workflowId": "${{ secrets.CODEMAGIC_WORKFLOW_PANEL }}",
            "branch": "main",
            "teamId": "${{ secrets.CODEMAGIC_TEAM_ID }}"
          }
          JSON
          echo "== POST /builds (fallback panel) =="
          curl -sS -i -X POST https://api.codemagic.io/builds \
            -H "Content-Type: application/json" \
            -H "x-auth-token: ${{ secrets.CODEMAGIC_TOKEN }}" \
            -d @payload.json
