name: Build APKs via Codemagic
on:
  workflow_dispatch:

jobs:
  smart:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Codemagic (smart-assistant-app)
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          app-id: ${{ secrets.CODEMAGIC_APP_SMART }}
          workflow-id: ${{ secrets.CODEMAGIC_WORKFLOW_SMART }}
          codemagic-token: ${{ secrets.CODEMAGIC_TOKEN }}

  panel:
    runs-on: ubuntu-latest
    needs: smart
    steps:
      - name: Trigger Codemagic (control-panel-app)
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          app-id: ${{ secrets.CODEMAGIC_APP_PANEL }}
          workflow-id: ${{ secrets.CODEMAGIC_WORKFLOW_PANEL }}
          codemagic-token: ${{ secrets.CODEMAGIC_TOKEN }}
