name: Trigger Autopilot Workflow

on:
  push:
    branches: [ main ]
    paths:
      - "apps/**"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Autopilot Repo Build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/ibrahimalsattouf88-lab/ibrahimalsattouf88-lab-smart-assistant-autopilot/dispatches \
            -d '{"event_type":"trigger_from_meta"}'
