name: Verify Secrets
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: List required secrets presence (masked)
        run: |
          check() { var="$1"; if [ -z "${!var}" ]; then echo "❌ MISSING $var"; exit 1; else echo "✅ $var OK"; fi }
          export CODEMAGIC_API_TOKEN="${{ secrets.CODEMAGIC_API_TOKEN }}"
          export CODEMAGIC_TEAM_ID="${{ secrets.CODEMAGIC_TEAM_ID }}"
          export CODEMAGIC_APP_ID="${{ secrets.CODEMAGIC_APP_ID }}"
          export CODEMAGIC_CONTROL_PANEL_ID="${{ secrets.CODEMAGIC_CONTROL_PANEL_ID }}"
          export CODEMAGIC_WORKFLOW_ID_SMART_ASSISTANT="${{ secrets.CODEMAGIC_WORKFLOW_ID_SMART_ASSISTANT }}"
          export CODEMAGIC_WORKFLOW_ID_CONTROL_PANEL="${{ secrets.CODEMAGIC_WORKFLOW_ID_CONTROL_PANEL }}"
          check CODEMAGIC_API_TOKEN
          check CODEMAGIC_TEAM_ID
          check CODEMAGIC_APP_ID
          check CODEMAGIC_CONTROL_PANEL_ID
          check CODEMAGIC_WORKFLOW_ID_SMART_ASSISTANT
          check CODEMAGIC_WORKFLOW_ID_CONTROL_PANEL
